{
    "swagger": "2.0",
    "info": {
        "title": "Library Management API",
        "description": "API for managing a library system",
        "version": "1.0.0"
    },
    "paths": {
        "/books": {
            "get": {
                "summary": "List all books",
                "responses": {
                    "200": {
                        "description": "A list of books"
                    }
                }
            },
            "post": {
                "summary": "Add a new book",
                "parameters": [
                    {
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Book"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Book added"
                    }
                }
            }
        },
        "/books/{isbn}": {
            "get": {
                "summary": "Retrieve a book by ISBN",
                "parameters": [
                    {
                        "name": "isbn",
                        "in": "path",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Book retrieved"
                    },
                    "404": {
                        "description": "Book not found"
                    }
                }
            },
            "put": {
                "summary": "Update a book by ISBN",
                "parameters": [
                    {
                        "name": "isbn",
                        "in": "path",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Book"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Book updated"
                    },
                    "404": {
                        "description": "Book not found"
                    }
                }
            },
            "delete": {
                "summary": "Delete a book by ISBN",
                "parameters": [
                    {
                        "name": "isbn",
                        "in": "path",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Book deleted"
                    },
                    "404": {
                        "description": "Book not found"
                    }
                }
            }
        }
    },
    "definitions": {
        "Book": {
            "type": "object",
            "properties": {
                "title": { "type": "string" },
                "author": { "type": "string" },
                "published_year": { "type": "integer" },
                "isbn": { "type": "string" },
                "genre": { "type": "string" }
            }
        }
    }
}
